# Generated by Django 5.1.4 on 2024-12-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('LIGHT', 'Light'), ('TEMP', 'Temperature'), ('HUMID', 'Humidity'), ('CURTAIN', 'Curtain'), ('MOTION', 'Motion Sensor'), ('SMOKE', 'Smoke Detector')], max_length=20)),
                ('status', models.CharField(default='OFF', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
